name: CI

on: [push]

jobs:
  build:

    runs-on: {{ '${{ matrix.os }}' }}
    strategy:
      max-parallel: 4
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v1

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a

{% if cookiecutter.dependency_source == 'Dependencies from pip only (no conda)' %}
    - name: Install testing dependencies
      shell: bash
      run: |
        python -m pip install -U pytest pytest-cov codecov
{% else %}
    - name: Create environment for package
      shell: bash
      run: |
        eval "$(${CONDA}/conda shell.bash hook)" && conda activate
        python devtools/scripts/create_conda_env.py -n=test -p={{ '${{ matrix.python-version }}' }} devtools/conda-envs/test_env.yaml
{% endif %}

    - name: Install package
      shell: bash
      run: |
{% if cookiecutter.dependency_source == 'Dependencies from pip only (no conda)' %}
        python -m pip install .
{% else %}
        eval "$(${CONDA}/conda shell.bash hook)" && conda activate test
        python -m pip install . --no-deps
{% endif %}

    - name: Run tests
      shell: bash
      run: |
{% if cookiecutter.dependency_source != 'Dependencies from pip only (no conda)' %}
        eval "$(${CONDA}/bin/conda shell.bash hook)" && conda activate test
{% endif %}
        pytest -v --cov={{ cookiecutter.repo_name }} {{ cookiecutter.repo_name }}/tests/

    - name: Code coverage
      shell: bash
      run: |
{% if cookiecutter.dependency_source != 'Dependencies from pip only (no conda)' %}
        eval "$(${CONDA}/bin/conda shell.bash hook)" && conda activate test
{% endif %}
        codecov
