name: Pseudo Validate GHA Output

# Approximation of the GHA "on" block
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  schedule:
    # Nightly tests run on master by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * *"

# Custom global env block
env:
  licenses: [1, 2]
  depend-sources: [1, 2, 3]
  ci-providers: 3  # This should always be GHA and only GHA
  rtd: [1, 2]

jobs:
  generate-cookiecutter:
    name: "Cookiecutter Artifacts"
    strategy:
      matrix:
        license: ${{ env.licenses }}
        depend-source: ${{ env.depend-sources }}
        ci-provider: ${{ env.ci-providers }}
        rtd: ${{ env.rtd }}
    steps:
      - uses: actions/checkout@v1

      - name: "Install dependencies"
        shell: bash
        run: |
          python -m pip install -U pyyaml cookiecutter

      - name: "Construct Cookiecutter"
        shell: bash
        run: |
          python tests/setup_cookiecutter.py built_cookie_{{ '${{ matrix.license }}' }}_{{ '${{ matrix.depend-source }}' }}_{{ '${{ matrix.ci-provider }}' }}_{{ '${{ matrix.rtd }}' }} {{ '${{ matrix.license }}' }} {{ '${{ matrix.depend-source }}' }} {{ '${{ matrix.ci-provider }}' }} {{ '${{ matrix.rtd }}' }}

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: cookiecutter_outputs
          path: built_cookie_{{ '${{ matrix.license }}' }}_{{ '${{ matrix.depend-source }}' }}_{{ '${{ matrix.ci-provider }}' }}_{{ '${{ matrix.rtd }}' }}

  compare-action-output:
    name: "Compare GHA Output"
    needs: "generate-cookiecutter"
    strategy:
      matrix:
        license: ${{ env.licenses }}
        depend-source: ${{ env.depend-sources }}
        ci-provider: ${{ env.ci-providers }}
        rtd: ${{ env.rtd }}

    steps:
      - uses: actions/checkout@v1

      - name: "Fetch Artifacts"
        uses: actions/download-artifact@v2
        with:
          name: cookiecutter_outputs

      - name: "Compare Reference CI"
        shell: bash
        run: |
          COMBO="{{ '${{ matrix.license }}' }}_{{ '${{ matrix.depend-source }}' }}_{{ '${{ matrix.ci-provider }}' }}_{{ '${{ matrix.rtd }}' }}"
          mv built_cookie_$COMBO/.github/workflows/CI.yaml CI_$COMBO.yaml
          COMPARE=$(diff CI_$COMBO.yaml .github/reference-workflows/CI_$COMBO.yaml)
          if [[ ! -z $COMPARE ]]
          then
              echo "CI_$COMBO.yaml differs from reference!"
              echo $COMPARE
              exit 1


  conda-forge-dep:
    needs: "generate-cookiecutter"
    name: Test CF (Approx) on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:  # Approximate strategy, uses a few other options
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7]
        license: 1  # Nonstandard
        rtd: ${{ env.rtd }}  # Nonstandard
    steps:
      # - uses: actions/checkout@v1  # This isn't necessary here

      - name: "Fetch Artifacts"
        uses: actions/download-artifact@v2
        with:
          name: cookiecutter_outputs

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: "Change directory"  # Have to CD here to make sure this works
        shell: bash
        run: |
          cd built_cookie_{{ '${{ matrix.license }}' }}_1_3_{{ '${{ matrix.rtd }}' }}

      # More info on options: https://github.com/conda-incubator/setup-miniconda
      - uses: conda-incubator/setup-miniconda@v1
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: devtools/conda-envs/test_env.yaml

          channels: conda-forge,defaults

          activate-environment: test
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Install package

        # conda setup requires this special shell
        shell: bash -l {0}
        run: |
          python -m pip install . --no-deps
          conda list


      - name: Run tests

        # conda setup requires this special shell
        shell: bash -l {0}
        run: |
          pytest -v --cov=built_cookie_{ '${{ matrix.license }}' }}_1_${{ env.ci-providers }}_{{ '${{ matrix.rtd }}' }} --cov-report=xml --color=yes built_cookie_{{ '${{ matrix.license }}' }}_1_${{ env.ci-providers }}_{{ '${{ matrix.rtd }}' }}/tests/

      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}


  conda-defaults-dep:
    needs: "generate-cookiecutter"
    name: Test Conda Defaults (Approx) on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:  # Approximate strategy, uses a few other options
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7]
        license: 1  # Nonstandard
        rtd: ${{ env.rtd }}  # Nonstandard

    steps:
      # - uses: actions/checkout@v1  # This isn't necessary here

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: "Fetch Artifacts"
        uses: actions/download-artifact@v2
        with:
          name: cookiecutter_outputs

      - name: "Change directory"  # Have to CD here to make sure this works
        shell: bash
        run: |
          cd built_cookie_{{ '${{ matrix.license }}' }}_2_${{ env.ci-providers }}_{{ '${{ matrix.rtd }}' }}

      # More info on options: https://github.com/conda-incubator/setup-miniconda
      - uses: conda-incubator/setup-miniconda@v1
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: devtools/conda-envs/test_env.yaml

          activate-environment: test
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Install package

        # conda setup requires this special shell
        shell: bash -l {0}
        run: |
          python -m pip install . --no-deps
          conda list


      - name: Run tests

        # conda setup requires this special shell
        shell: bash -l {0}

        run: |
          pytest -v --cov=built_cookie_{ '${{ matrix.license }}' }}_2_${{ env.ci-providers }}_{{ '${{ matrix.rtd }}' }} --cov-report=xml --color=yes built_cookie_{{ '${{ matrix.license }}' }}_2_${{ env.ci-providers }}_{{ '${{ matrix.rtd }}' }}/tests/

      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}

  pip-dep:
    needs: "generate-cookiecutter"
    name: Test Pip (Approx) on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:  # Approximate strategy, uses a few other options
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7]
        license: 1  # Nonstandard
        rtd: ${{ env.rtd }}  # Nonstandard

    steps:
      # - uses: actions/checkout@v1  # This isn't necessary here

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: "Fetch Artifacts"
        uses: actions/download-artifact@v2
        with:
          name: cookiecutter_outputs

      - name: "Change directory"  # Have to CD here to make sure this works
        shell: bash
        run: |
          cd built_cookie_{{ '${{ matrix.license }}' }}_3_${{ env.ci-providers }}_{{ '${{ matrix.rtd }}' }}


      - name: Testing Dependencies
        shell: bash
        run: |
          python -m pip install -U pytest pytest-cov codecov

      - name: Install package

        shell: bash
        run: |
          python -m pip install .


      - name: Run tests

        shell: bash

        run: |
          pytest -v --cov=built_cookie_{ '${{ matrix.license }}' }}_3_${{ env.ci-providers }}_{{ '${{ matrix.rtd }}' }} --cov-report=xml --color=yes built_cookie_{{ '${{ matrix.license }}' }}_3_${{ env.ci-providers }}_{{ '${{ matrix.rtd }}' }}/tests/

      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}